In [2]:
import pandas as pd

df = pd.read_csv('Vehicle Data.csv')

In [3]:
df.head(10)

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
0,Alabama,"13,000","5,800","63,300","54,200","441,200",100,100,0,0,"4,102,200","127,000","29,000"
1,Alaska,"2,700",900,"10,600","9,600","46,800",0,0,0,0,"454,300","29,800","5,100"
2,Arizona,"89,800","25,600","175,700","68,600","437,100",600,700,0,0,"5,469,000","197,700","64,200"
3,Arkansas,"7,100","3,200","37,000","37,000","276,700",200,0,0,0,"2,246,100","90,700","10,300"
4,California,"1,256,600","410,700","1,703,200","201,600","1,314,600","10,100","1,500","16,900",0,"31,191,900","735,300","7,900"
5,Colorado,"90,100","37,500","152,700","68,100","334,300",300,100,0,0,"4,508,800","203,400","46,500"
6,Connecticut,"31,600","18,400","75,300","10,900","133,600",100,0,0,0,"2,612,600","42,300","20,900"
7,Delaware,"8,400","3,800","22,900","5,100","63,900",0,0,0,0,"791,300","14,200","5,100"
8,District of Columbia,"8,100","3,700","18,100",400,"16,800",100,0,0,0,"262,500","1,800",600
9,Florida,"254,900","57,300","414,500","170,500","1,101,100",400,100,0,0,"16,136,500","351,800","96,100"

In [4]:
df = df.drop(index=8)

df.head(10)

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
0,Alabama,"13,000","5,800","63,300","54,200","441,200",100,100,0,0,"4,102,200","127,000","29,000"
1,Alaska,"2,700",900,"10,600","9,600","46,800",0,0,0,0,"454,300","29,800","5,100"
2,Arizona,"89,800","25,600","175,700","68,600","437,100",600,700,0,0,"5,469,000","197,700","64,200"
3,Arkansas,"7,100","3,200","37,000","37,000","276,700",200,0,0,0,"2,246,100","90,700","10,300"
4,California,"1,256,600","410,700","1,703,200","201,600","1,314,600","10,100","1,500","16,900",0,"31,191,900","735,300","7,900"
5,Colorado,"90,100","37,500","152,700","68,100","334,300",300,100,0,0,"4,508,800","203,400","46,500"
6,Connecticut,"31,600","18,400","75,300","10,900","133,600",100,0,0,0,"2,612,600","42,300","20,900"
7,Delaware,"8,400","3,800","22,900","5,100","63,900",0,0,0,0,"791,300","14,200","5,100"
9,Florida,"254,900","57,300","414,500","170,500","1,101,100",400,100,0,0,"16,136,500","351,800","96,100"
10,Georgia,"92,400","22,700","175,300","92,500","719,400",300,200,0,0,"8,256,400","206,300","76,900"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 50
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           50 non-null     object
 1   Electric (EV)                   50 non-null     object
 2   Plug-In Hybrid Electric (PHEV)  50 non-null     object
 3   Hybrid Electric (HEV)           50 non-null     object
 4   Biodiesel                       50 non-null     object
 5   Ethanol/Flex (E85)              50 non-null     object
 6   Compressed Natural Gas (CNG)    50 non-null     object
 7   Propane                         50 non-null     object
 8   Hydrogen                        50 non-null     object
 9   Methanol                        50 non-null     int64
 10  Gasoline                        50 non-null     object
 11  Diesel                          50 non-null     object
 12  Unknown Fuel                    50 non-null     object
dtypes: int64(1), object(12)
memory usage: 5.5+ KB

In [6]:
# set object rows to int by removing commas and changing data type

cols_to_convert = df.columns.drop("State")

df[cols_to_convert] = (
    df[cols_to_convert]
    .replace(",", "", regex=True)
    .apply(pd.to_numeric, errors="coerce")
    .astype("Int64")
)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 50
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   State                           50 non-null     object
 1   Electric (EV)                   50 non-null     Int64
 2   Plug-In Hybrid Electric (PHEV)  50 non-null     Int64
 3   Hybrid Electric (HEV)           50 non-null     Int64
 4   Biodiesel                       50 non-null     Int64
 5   Ethanol/Flex (E85)              50 non-null     Int64
 6   Compressed Natural Gas (CNG)    50 non-null     Int64
 7   Propane                         50 non-null     Int64
 8   Hydrogen                        50 non-null     Int64
 9   Methanol                        50 non-null     Int64
 10  Gasoline                        50 non-null     Int64
 11  Diesel                          50 non-null     Int64
 12  Unknown Fuel                    50 non-null     Int64
dtypes: Int64(12), object(1)
memory usage: 6.1+ KB

In [7]:
df.describe(include='all')

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel,Unknown Fuel
count,50,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0
unique,50,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
top,Alabama,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
freq,1,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
mean,NaN,70956.0,26070.0,147484.0,56064.0,404476.0,492.0,120.0,338.0,0.0,4852168.0,143650.0,33870.0
std,NaN,179996.240505,58503.337599,247767.012316,68971.516629,396971.533735,1451.507309,292.770022,2390.02092,0.0,5503789.66811,145190.66177,25817.999179
min,NaN,1000.0,800.0,8200.0,3100.0,36600.0,0.0,0.0,0.0,0.0,454300.0,11000.0,3700.0
25%,NaN,8250.0,4950.0,36500.0,22925.0,127425.0,100.0,0.0,0.0,0.0,1575850.0,63075.0,13400.0
50%,NaN,25850.0,11750.0,79200.0,44450.0,332800.0,200.0,0.0,0.0,0.0,3491250.0,116550.0,27700.0
75%,NaN,71625.0,29025.0,175025.0,67125.0,531250.0,300.0,100.0,0.0,0.0,5611125.0,173425.0,46650.0
max,NaN,1256600.0,410700.0,1703200.0,460700.0,2315400.0,10100.0,1500.0,16900.0,0.0,31191900.0,772800.0,121800.0

In [8]:
df.isnull().sum()

State                             0
Electric (EV)                     0
Plug-In Hybrid Electric (PHEV)    0
Hybrid Electric (HEV)             0
Biodiesel                         0
Ethanol/Flex (E85)                0
Compressed Natural Gas (CNG)      0
Propane                           0
Hydrogen                          0
Methanol                          0
Gasoline                          0
Diesel                            0
Unknown Fuel                      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
# set all columns to snake case

df.columns = df.columns.str.lower() # sets all columns to lowercase
df.columns = df.columns.str.replace(' ','_') # replaces all spaces with underscores


df.columns = df.columns.str.replace(r"\s*\(.*", "", regex=True) # removes everything after parentheses in column names
df.columns = df.columns.str.replace(r"_$", "", regex=True) # removes underscores *that are at the end of some columns* using $ 


df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,methanol,gasoline,diesel,unknown_fuel
0,Alabama,13000,5800,63300,54200,441200,100,100,0,0,4102200,127000,29000
1,Alaska,2700,900,10600,9600,46800,0,0,0,0,454300,29800,5100
2,Arizona,89800,25600,175700,68600,437100,600,700,0,0,5469000,197700,64200
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,0,2246100,90700,10300
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,0,31191900,735300,7900

In [11]:
df = df.drop(columns=["unknown_fuel"])

In [12]:
df["methanol"].sum()

np.int64(0)

In [13]:
df = df.drop(columns=["methanol"])

df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,diesel
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,127000
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,29800
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,197700
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,90700
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,735300

## Cleaning Complete

### Now, I'll add in some columns that will aid in analysis down the line.

In [14]:
# adding a "total column"

fuel_cols = df.columns.drop("state")

df["total"] = df[fuel_cols].sum(axis=1)

df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,diesel,total
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,127000,4806900
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,29800,554700
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,197700,6464800
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,90700,2698000
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,735300,36842400

In [15]:
# adds alternative and traditional fuel columns - useful for traditional vs alternative fuel comp

alt_fuel_cols = [
    "electric",
    "plug-in_hybrid_electric",
    "hybrid_electric",
    "biodiesel",
    "ethanol/flex",
    "compressed_natural_gas",
    "propane",
    "hydrogen"
]

df["alternative_fuel_total"] = df[alt_fuel_cols].sum(axis=1)



df["traditional_fuel_total"] = df[["gasoline", "diesel"]].sum(axis=1)


electrified_cols = [
    "electric",
    "plug-in_hybrid_electric",
    "hybrid_electric"
]

df["electrified_total"] = df[electrified_cols].sum(axis=1)


df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,diesel,total,alternative_fuel_total,traditional_fuel_total,electrified_total
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,127000,4806900,577700,4229200,82100
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,29800,554700,70600,484100,14200
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,197700,6464800,798100,5666700,291100
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,90700,2698000,361200,2336800,47300
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,735300,36842400,4915200,31927200,3370500

In [16]:
# adds some % columns for an unbiased comparison (some states are larger than others. It's best to compare %'s rather than totals)

# alternative %
df["alternative_fuel_percent"] = (
    df["alternative_fuel_total"] / df["total"] * 100
)

# traditional %
df["traditional_fuel_percent"] = (
    df["traditional_fuel_total"] / df["total"] * 100
)

# electric %
df["electric_percent"] = df["electric"] / df["total"] * 100

# plug-in hybrid electric %
df["plug-in_hybrid_electric_percent"] = df["plug-in_hybrid_electric"] / df["total"] * 100

# hybrid electric %
df["hybrid_electric_percent"] = df["hybrid_electric"] / df["total"] * 100


# electrified %
df["electrified_percent"] = (
    df["electrified_total"] / df["total"] * 100
)

# gasoline %
df["gasoline_percent"] = df["gasoline"] / df["total"] * 100

# Diesel %
df["diesel_percent"] = df["diesel"] / df["total"] * 100


df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,...,traditional_fuel_total,electrified_total,alternative_fuel_percent,traditional_fuel_percent,electric_percent,plug-in_hybrid_electric_percent,hybrid_electric_percent,electrified_percent,gasoline_percent,diesel_percent
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,...,4229200,82100,12.018141,87.981859,0.270445,0.12066,1.316857,1.707961,85.339824,2.642035
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,...,484100,14200,12.727601,87.272399,0.48675,0.16225,1.910943,2.559942,81.900126,5.372273
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,...,5666700,291100,12.345316,87.654684,1.389061,0.395991,2.717795,4.502846,84.596585,3.058099
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,...,2336800,47300,13.387695,86.612305,0.263158,0.118606,1.371386,1.75315,83.250556,3.361749
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,...,31927200,3370500,13.34115,86.65885,3.410744,1.114748,4.622934,9.148427,84.663051,1.995798

In [17]:
# dominant alternative fuel type

df["dominant_alternative_fuel_type"] = df[alt_fuel_cols].idxmax(axis=1)


df.head()

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,...,electrified_total,alternative_fuel_percent,traditional_fuel_percent,electric_percent,plug-in_hybrid_electric_percent,hybrid_electric_percent,electrified_percent,gasoline_percent,diesel_percent,dominant_alternative_fuel_type
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,...,82100,12.018141,87.981859,0.270445,0.12066,1.316857,1.707961,85.339824,2.642035,ethanol/flex
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,...,14200,12.727601,87.272399,0.48675,0.16225,1.910943,2.559942,81.900126,5.372273,ethanol/flex
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,...,291100,12.345316,87.654684,1.389061,0.395991,2.717795,4.502846,84.596585,3.058099,ethanol/flex
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,...,47300,13.387695,86.612305,0.263158,0.118606,1.371386,1.75315,83.250556,3.361749,ethanol/flex
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,...,3370500,13.34115,86.65885,3.410744,1.114748,4.622934,9.148427,84.663051,1.995798,hybrid_electric

In [18]:
# final fheck

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 50
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   state                            50 non-null     object
 1   electric                         50 non-null     Int64
 2   plug-in_hybrid_electric          50 non-null     Int64
 3   hybrid_electric                  50 non-null     Int64
 4   biodiesel                        50 non-null     Int64
 5   ethanol/flex                     50 non-null     Int64
 6   compressed_natural_gas           50 non-null     Int64
 7   propane                          50 non-null     Int64
 8   hydrogen                         50 non-null     Int64
 9   gasoline                         50 non-null     Int64
 10  diesel                           50 non-null     Int64
 11  total                            50 non-null     Int64
 12  alternative_fuel_total           50 non-null     Int64
 13  traditional_fuel_total           50 non-null     Int64
 14  electrified_total                50 non-null     Int64
 15  alternative_fuel_percent         50 non-null     Float64
 16  traditional_fuel_percent         50 non-null     Float64
 17  electric_percent                 50 non-null     Float64
 18  plug-in_hybrid_electric_percent  50 non-null     Float64
 19  hybrid_electric_percent          50 non-null     Float64
 20  electrified_percent              50 non-null     Float64
 21  gasoline_percent                 50 non-null     Float64
 22  diesel_percent                   50 non-null     Float64
 23  dominant_alternative_fuel_type   50 non-null     object
dtypes: Float64(8), Int64(14), object(2)
memory usage: 10.8+ KB

In [19]:
df.head(10)

,state,electric,plug-in_hybrid_electric,hybrid_electric,biodiesel,ethanol/flex,compressed_natural_gas,propane,hydrogen,gasoline,...,electrified_total,alternative_fuel_percent,traditional_fuel_percent,electric_percent,plug-in_hybrid_electric_percent,hybrid_electric_percent,electrified_percent,gasoline_percent,diesel_percent,dominant_alternative_fuel_type
0,Alabama,13000,5800,63300,54200,441200,100,100,0,4102200,...,82100,12.018141,87.981859,0.270445,0.12066,1.316857,1.707961,85.339824,2.642035,ethanol/flex
1,Alaska,2700,900,10600,9600,46800,0,0,0,454300,...,14200,12.727601,87.272399,0.48675,0.16225,1.910943,2.559942,81.900126,5.372273,ethanol/flex
2,Arizona,89800,25600,175700,68600,437100,600,700,0,5469000,...,291100,12.345316,87.654684,1.389061,0.395991,2.717795,4.502846,84.596585,3.058099,ethanol/flex
3,Arkansas,7100,3200,37000,37000,276700,200,0,0,2246100,...,47300,13.387695,86.612305,0.263158,0.118606,1.371386,1.75315,83.250556,3.361749,ethanol/flex
4,California,1256600,410700,1703200,201600,1314600,10100,1500,16900,31191900,...,3370500,13.34115,86.65885,3.410744,1.114748,4.622934,9.148427,84.663051,1.995798,hybrid_electric
5,Colorado,90100,37500,152700,68100,334300,300,100,0,4508800,...,280300,12.66102,87.33898,1.669972,0.695049,2.830241,5.195263,83.569032,3.769948,ethanol/flex
6,Connecticut,31600,18400,75300,10900,133600,100,0,0,2612600,...,125300,9.227981,90.772019,1.080416,0.629103,2.574535,4.284054,89.325766,1.446253,ethanol/flex
7,Delaware,8400,3800,22900,5100,63900,0,0,0,791300,...,35100,11.444591,88.555409,0.923483,0.417766,2.51759,3.858839,86.994283,1.561126,ethanol/flex
9,Florida,254900,57300,414500,170500,1101100,400,100,0,16136500,...,726700,10.811863,89.188137,1.378799,0.309946,2.242104,3.930849,87.285188,1.902949,ethanol/flex
10,Georgia,92400,22700,175300,92500,719400,300,200,0,8256400,...,290400,11.528932,88.471068,0.965971,0.237311,1.832628,3.03591,86.314359,2.156709,ethanol/flex

In [ ]:
df. to_csv('Vehicle Data Cleaned.csv', index=False)

### Connect the notebook to PostgreSQL

### Load the data into PostgreSQL

In [24]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\domin\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\domin\appdata\local\programs\python\python313\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\domin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\domin\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

# Connect to PostgreSQL
# Replace placeholders w/ your actual details
username = "postgres"                   # default user
password = "_______"                 # password set during install
host = "localhost"                      # if running locally
port = "5432"                           # default port
database = "usa_vehicle_analysis"       # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Load Dataframe into PostgreSQL
table_name = "vehicle_analysis"         # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'vehicle_analysis' in database 'usa_vehicle_analysis'.